# Generated by Django 5.1 on 2025-01-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Termit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termi', models.CharField(default='termi', max_length=20)),
                ('term', models.CharField(default='term', max_length=20)),
                ('selitys', models.CharField(default='selitys', max_length=2000)),
            ],
        ),
    ]
